location = [450.37, 7991.98, 79512.66]  # ICARUS TPC center in NuMI coords [cm]
# location = [0, 0, 103648.837]  # 2x2

output_file = "output.root"

pot_per_file = 500_000

# list of branches to save in the tree. No Tree is saved if this is empty. If set to ["*"], all branches are saved.
# save_branches = ["nu_pdg", "nu_energy", "weight"]
# save_branches = ["*"]
save_branches = []

[file_sets]
# fhc = "/pnfs/icarus/persistent/users/awood/2024-06-27_numi_beamsim_g4.10/me000z200i/run0/g4numi*.root"
run0_fhc = "/pnfs/icarus/persistent/users/awood/g4numi_g4_10_4_p02d_nothresh/me000z200i/run0/files/g4numi*.root"
# run1_fhc = "/pnfs/icarus/persistent/users/awood/g4numi_g4_10_4_p02d_nothresh/me000z200i/run1/files/g4numi*.root"
# run2_fhc = "/pnfs/icarus/persistent/users/awood/g4numi_g4_10_4_p02d_nothresh/me000z200i/run2/files/g4numi*.root"
# run3_fhc = "/pnfs/icarus/persistent/users/awood/g4numi_g4_10_4_p02d_nothresh/me000z200i/run3/files/g4numi*.root"


[aliases]
# Rename quantities for easier access.
# see ROOT::RDataFrame::Alias
nu_pdg     = "dk2nu.decay.ntype"
parent_pdg = "dk2nu.decay.ptype"
vx         = "dk2nu.decay.vx"
vy         = "dk2nu.decay.vy"
vz         = "dk2nu.decay.vz"
pdpx       = "dk2nu.decay.pdpx"
pdpy       = "dk2nu.decay.pdpy"
pdpz       = "dk2nu.decay.pdpz"

[filters]
# Define filters to apply to the entries
# see ROOT::RDataFrame::Filter
no_dar = "parent_momentum > 0."

[definitions]
# Define quantities to calculate
# see ROOT::RDataFrame::Define
is_numu           = "nu_pdg == 14"
is_numubar        = "nu_pdg == -14"
is_nue            = "nu_pdg == 12"
is_nuebar	      = "nu_pdg == -12"
is_pipm           = "abs(parent_pdg) == 211"
is_Kpm            = "abs(parent_pdg) == 321"
is_muon           = "abs(parent_pdg) == 13"
is_K0             = "parent_pdg == 310 || parent_pdg == 130"
parent_momentum   = "sqrt(pdpx*pdpx + pdpy*pdpy + pdpz*pdpz)"
# ancestor_vol      = "get_volumes(dk2nu.ancestor)"
decay_vertex      = "ROOT::RVec<double>{vx, vy, vz}"
rr                = "det_loc - decay_vertex"
v_parent_momentum = "ROOT::RVec<double>{pdpx, pdpy, pdpz}"
sangdet           = "Numba::calc_solid_angle(rr)"                         # Solid angle as fraction of 4pi
costh 		      = "Numba::calc_costheta_par(v_parent_momentum, rr)"     # Cosine of the angle between the parent particle and the detector component
parent_mass       = "Numba::pdg_to_mass(parent_pdg)"
parent_energy     = "Numba::calc_energy(v_parent_momentum, parent_mass)"  # Calculate the energy of the parent particle at the decay vertex
pgamma            = "Numba::calc_gamma(parent_energy, parent_mass)"       # Calculate the gamma factor of the parent particle
emrat             = "Numba::calc_energy_in_beam(pgamma, costh)"           # Weighted neutrino energy in the lab frame. Small angle approximation.
nu_energy         = "dk2nu.decay.necm * emrat"                            # Lorentz boost the neutrino energy into the lab frame
flux_wgt          = "calc_weight(dk2nu.decay, sangdet, emrat, parent_energy, nu_energy, pgamma, rr)"
flux_wgt_POT      = "pot_wgt*flux_wgt"
theta_p           = "Numba::theta_p(v_parent_momentum, det_loc)"
# par_codes = "Numba::parent_to_code(dk2nu.ancestor.pdg)"
# target_codes = "Numba::target_to_code(dk2nu.ancestor.nucleus)"
# ancestor_parent_pdg = "Numba::ancestor_parent_pdg(dk2nu.ancestor.pdg)"
# ancestor_parent_mom = "Numba::calc_magnitudes(dk2nu.ancestor.pprodpx, dk2nu.ancestor.pprodpy, dk2nu.ancestor.pprodpz)"
# ancestor_parent_mom = "get_incident_momenta(dk2nu.ancestor)"
# ancestor_produced_mom = "get_produced_momenta(dk2nu.ancestor)"
# ancestor_produced_theta = "calc_theta(dk2nu.ancestor)"
# ancestor_mass = "Numba::ancestor_pdg2mass(dk2nu.ancestor.pdg)"
# ancestor_pT = "calc_pT(dk2nu.ancestor)"
# ancestor_xF = "calc_xF(dk2nu.ancestor, ancestor_mass)"

[histograms]
# Define histograms to create
# see ROOT::RDataFrame::Histo1D or ::Histo2D

# Flux vs. Neutrino Energy Spectra

[histograms.h_Enu_numu]
dir = "flux_Enu"
title = "#nu_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
bins = [200, 0, 20]
var = "nu_energy"
weight = "flux_wgt_POT"
filter = "is_numu"

[histograms.h_Enu_numu_pipm]
copy_from = "h_Enu_numu"
title = "#pi^{+} #rightarrow #nu_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numu*is_pipm"

[histograms.h_Enu_numu_Kpm]
copy_from = "h_Enu_numu"
title = "K^{+} #rightarrow #nu_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numu*is_Kpm"

[histograms.h_Enu_numu_K0]
copy_from = "h_Enu_numu"
title = "K^{0}_{L} #rightarrow #nu_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numu*is_K0"

[histograms.h_Enu_numu_mupm]
copy_from = "h_Enu_numu"
title = "#mu^{-} #rightarrow #nu_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numu*is_muon"

[histograms.h_Enu_numubar]
copy_from = "h_Enu_numu"
title = "#bar{#nu}_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numubar"

[histograms.h_Enu_numubar_pipm]
copy_from = "h_Enu_numu"
title = "#pi^{+} #rightarrow #bar{#nu}_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numubar*is_pipm"

[histograms.h_Enu_numubar_Kpm]
copy_from = "h_Enu_numu"
title = "K^{+} #rightarrow #bar{#nu}_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numubar*is_Kpm"

[histograms.h_Enu_numubar_K0]
copy_from = "h_Enu_numu"
title = "K^{0}_{L} #rightarrow #bar{#nu}_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numubar*is_K0"

[histograms.h_Enu_numubar_mupm]
copy_from = "h_Enu_numu"
title = "#mu^{+} #rightarrow #bar{#nu}_{#mu};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_numubar*is_muon"

[histograms.h_Enu_nue]
copy_from = "h_Enu_numu"
title = "#nu_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nue"

[histograms.h_Enu_nue_Kpm]
copy_from = "h_Enu_numu"
title = "K^{+} #rightarrow #nu_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nue*is_Kpm"

[histograms.h_Enu_nue_K0]
copy_from = "h_Enu_numu"
title = "K^{0}_{L} #rightarrow #nu_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nue*is_K0"

[histograms.h_Enu_nue_mupm]
copy_from = "h_Enu_numu"
title = "#mu^{-} #rightarrow #nu_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nue*is_muon"

[histograms.h_Enu_nuebar]
copy_from = "h_Enu_numu"
title = "#bar{#nu}_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nuebar"

[histograms.h_Enu_nuebar_Kpm]
copy_from = "h_Enu_numu"
title = "K^{+} #rightarrow #bar{#nu}_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nuebar*is_Kpm"

[histograms.h_Enu_nuebar_K0]
copy_from = "h_Enu_numu"
title = "K^{0}_{L} #rightarrow #bar{#nu}_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nuebar*is_K0"

[histograms.h_Enu_nuebar_mupm]
copy_from = "h_Enu_numu"
title = "#mu^{+} #rightarrow #bar{#nu}_{e};E_{#nu} [GeV];d#Phi/dE_{#nu} [m^{-2} POT^{-1}]"
filter = "is_nuebar*is_muon"

# Parent decay momentum angle w.r.t. NuMI beam direction

[histograms.h_thetapar_numu_pipm]
dir = "parent_angle"
title = "#pi^{+} #rightarrow #nu_{#mu};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
bins = [100, -500, 500]
var = "theta_p"
weight = "flux_wgt_POT"
filter = "is_numu*is_pipm"

[histograms.h_thetapar_numu_Kpm]
copy_from = "h_thetapar_numu_pipm"
title = "K^{+} #rightarrow #nu_{#mu};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
filter = "is_numu*is_Kpm"

[histograms.h_thetapar_numu_K0]
copy_from = "h_thetapar_numu_pipm"
title = "K^{0}_{L} #rightarrow #nu_{#mu};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
filter = "is_numu*is_K0"

[histograms.h_thetapar_numu_mupm]
copy_from = "h_thetapar_numu_pipm"
title = "#mu^{-} #rightarrow #nu_{#mu};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
filter = "is_numu*is_muon"

[histograms.h_thetapar_nue_Kpm]
copy_from = "h_thetapar_numu_pipm"
title = "K^{+} #rightarrow #nu_{e};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
filter = "is_nue*is_Kpm"

[histograms.h_thetapar_nue_K0]
copy_from = "h_thetapar_numu_pipm"
title = "K^{0}_{L} #rightarrow #nu_{e};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
filter = "is_nue*is_K0"

[histograms.h_thetapar_nue_mupm]
copy_from = "h_thetapar_numu_pipm"
title = "#mu^{-} #rightarrow #nu_{e};#theta_{p} [mrad];d#Phi/d#theta_{p} [m^{-2} mrad^{-1} POT^{-1}]"
filter = "is_nue*is_muon"

[histograms.h_thetapar_Enu_numu_Kpm]
dir = "parent_angle"
title = "h_thetapar_Enu_numu_Kpm;#theta_{parent} [mrad];E_{#nu} [GeV]"
xbins = [1000, -500.0, 500.0]
ybins = [100, 0, 10]
xvar = "theta_p"
yvar = "nu_energy"
weight = "flux_wgt_POT"
filter = "is_numu*is_Kpm"
