location = [
    [450.37, 7991.98, 79512.66],  # ICARUS TPC center in NuMI coords [cm]
    # [450.37, 7833.84, 79521.90], # ICARUS TPC bot
    # [450.37, 8150.12, 79503.42] # ICARUS TPC Top
    # [0, 0, 103648.837]  # 2x2/on-axis
]

output_file = "/exp/icarus/app/users/faabdalr/fixed_fhc_rhc_run0_F.root"

#output_file = "/exp/icarus/data/users/faabdalr/uniform_beam_fhc_test.root"
#output_file = "/exp/icarus/data/users/faabdalr/gaussian_beam_fhc.root"

#output_file = "/exp/icarus/data/users/faabdalr/fixed_numiflux_rhc_1p5.root"
#output_file = "/exp/icarus/data/users/faabdalr/fixed_numiflux_fhc_1p5_run1_run5.root"

#output_file = "/exp/icarus/data/users/faabdalr/nofixed_run0_1p5.root"
#output_file = "/exp/icarus/data/users/faabdalr/numiflux_fhc_histograms_1p5_test.root"

#output_file = "/exp/icarus/data/users/faabdalr/fhc_g3Chase_test.root"
#output_file = "/exp/icarus/data/users/faabdalr/on_axis_output.root"


# list of branches to save in the tree. No Tree is saved if this is empty. If set to ["*"], all branches are saved.
# save_branches = ["nu_pdg", "nu_energy", "weight"]
# save_branches = ["*"]
save_branches = []

# max_files = 1  # set this if you want to limit the number of files read
[file_sets]
#run0_fhc = "/path/to/my/files/*.root" ## OVERRIDE THIS

#run0_fhc = "/pnfs/icarus/persistent/users/faabdalr/numi_beamsim/fhc/run0/g4numi_minervame_me000z200i_138_1488543658_20250327174941_0000.root"
run0_fhc = "/pnfs/icarus/persistent/users/faabdalr/numi_beamsim/fhc/run0/g4numi*.root"
run0_rhc = "/pnfs/icarus/persisten/users/faabdalr/numi_beamsim/rhc/run0/g4numi*.root"

#run0_rhc = "/pnfs/numix/flux/g4numi_syst_3rd_ana/test_g4numi_v6/me000z-200i/minervame/run0015/g4numi*.root"
#run0_fhc = "/pnfs/numix/flux/g4numi_syst_3rd_ana/test_g4numi_v6/me000z200i/minervame/run0015/g4numi*.root"
#run0_rhc = "/pnfs/icarus/scratch/users/faabdalr/v03_01_RHC/g4numi*.root"
#run0_fhc = "/pnfs/icarus/scratch/users/faabdalr/v03_01/g4numi*.root"
#run0_fhc = "/pnfs/sbn/persistent/stash/physics/beam/GENIE/NuMI/standard/v03_01"
#run0_rhc = "/pnfs/icarus/persistent/users/faabdalr/rhc_numi_beamsim_1p5/run0/g4numi*.root"
#run0_rhc = "/pnfs/icarus/scratch/users/faabdalr/numi_beamsim_rhc_run0_1p3/g4numi*.root"
#run0_fhc = "/pnfs/icarus/persistent/users/faabdalr/numi_beamsim_1p3/run0/g4numi*.root"

#run0_fhc = "/pnfs/icarus/persistent/users/faabdalr/fhc_numi_beamsim/run0/g4numi*.root"
#run1_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run1/g4numi*.root"
#run2_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run2/g4numi*.root"
#run3_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run3/g4numi*.root"
#run4_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run4/g4numi*.root"
#run5_fhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/fhc/run5/g4numi*.root"
#run6_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run6/g4numi*.root"
#run7_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run7/g4numi*.root"
#run8_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run8/g4numi*.root"
#run9_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run9/g4numi*.root"
#run10_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run10/g4numi*.root"
#run11_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run11/g4numi*.root"
#run12_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run12/g4numi*.root"
#run13_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run13/g4numi*.root"
#run14_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run14/g4numi*.root"
#run15_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run15/g4numi*.root"
#run16_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run16/g4numi*.root"
#run17_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run17/g4numi*.root"
#run18_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run18/g4numi*.root"
#run19_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run19/g4numi*.root"
#run20_fhc = "/pnfs/icarus/persistent/users/faabdalr/fixed_numi_beamsim/fhc/run20/g4numi*.root"


#run0_rhc = /pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run0/g4numi*.root"
#run1_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run1/g4numi*.root"
#run2_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run2/g4numi*.root"
#run3_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run3/g4numi*.root"
#run4_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run4/g4numi*.root"
#run5_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run5/g4numi*.root"
#run6_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run6/g4numi*.root"
#run7_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run7/g4numi*.root"
#run8_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run8/g4numi*.root"
#run9_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run9/g4numi*.root"
#run10_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run10/g4numi*.root"
#run11_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run11/g4numi*.root"
#run12_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run12/g4numi*.root"
#run13_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run13/g4numi*.root"
#run14_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run14/g4numi*.root"
#run15_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run15/g4numi*.root"
#run16_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run16/g4numi*.root"
#run17_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run17/g4numi*.root"
#run18_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run18/g4numi*.root"
#run19_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run19/g4numi*.root"
#run20_rhc = "/pnfs/icarus/scratch/users/faabdalr/fixed_numi_beamsim/rhc/run20/g4numi*.root"



[aliases]
# Rename quantities for easier access.
# see ROOT::RDataFrame::Alias
nu_pdg     = "dk2nu.decay.ntype"
parent_pdg = "dk2nu.decay.ptype"
vx         = "dk2nu.decay.vx"
vy         = "dk2nu.decay.vy"
vz         = "dk2nu.decay.vz"
pdpx       = "dk2nu.decay.pdpx"
pdpy       = "dk2nu.decay.pdpy"
pdpz       = "dk2nu.decay.pdpz"
#ppvx       = "dk2nu.ppvx"
#ppvy       = "dk2nu.ppvy"
#ppvz       = "dk2nu.ppvz"

[filters]
# Define filters to apply to the entries
# see ROOT::RDataFrame::Filter
no_dar = "parent_momentum > 0."

[definitions]
# Define quantities to calculate
# see ROOT::RDataFrame::Define
is_numu           = "nu_pdg == 14"
is_numubar        = "nu_pdg == -14"
is_nue            = "nu_pdg == 12"
is_nuebar	  = "nu_pdg == -12"
is_p              = "abs(parent_pdg) == 2212"
is_pipm           = "abs(parent_pdg) == 211"
is_Kpm            = "abs(parent_pdg) == 321"
is_muon           = "abs(parent_pdg) == 13"
is_K0             = "parent_pdg == 310 || parent_pdg == 130"
parent_momentum   = "sqrt(pdpx*pdpx + pdpy*pdpy + pdpz*pdpz)"
ancestor_vol      = "get_volumes(dk2nu.ancestor)"
decay_vertex      = "ROOT::RVec<double>{vx, vy, vz}"
rr                = "det_loc - decay_vertex"
baseline          = "Numba::calc_magnitude(rr)/100.0"             # Distance from the decay vertex to the detector
v_parent_momentum = "ROOT::RVec<double>{pdpx, pdpy, pdpz}"
nu_energy         = "neutrino_energy(decay, det_loc)"             # [GeV] Boost the neutrino energy into the lab frame
flux_wgt          = "calc_weight(decay, det_loc)"                 # [m^-2]
# pot_wgt is calculated at runtime as 1/total POT.
flux_wgt_pot      = "pot_wgt*flux_wgt"                            # flux_wgt / total POT
theta_p           = "Numba::theta_p(v_parent_momentum, det_loc)"  # [deg] Neutrino's primary parent trajectory w.r.t. NuMI axis at decay vertex
proton_startx = "dk2nu.ancestor[0].startx"
proton_starty = "dk2nu.ancestor[0].starty"
proton_startz = "dk2nu.ancestor[0].startz"
proton_stopx1 = "dk2nu.ancestor[1].startx"  # approximating stop position by the start pos of the particle produced by the beam proton (index = 1 as opposed to index = 0)
proton_stopy1 = "dk2nu.ancestor[1].starty"
proton_stopz1 = "dk2nu.ancestor[1].startz"
par_codes = "Numba::parent_to_code(dk2nu.ancestor.pdg)"
target_codes = "Numba::target_to_code(dk2nu.ancestor.nucleus)"
#ancestor_vol = "get_volumes(dk2nu.ancestor)"
#ancestor_parent_mom = "Numba::calc_magnitudes(dk2nu.ancestor.pprodpx, dk2nu.ancestor.pprodpy, dk2nu.ancestor.pprodpz)"
ancestor_parent_pdg = "Numba::ancestor_parent_pdg(dk2nu.ancestor.pdg)"
ancestor_incident_pdg = "Numba::incident_pdg_codes(dk2nu.ancestor.pdg)"
ancestor_produced_pdg = "Numba::produced_pdg_codes(dk2nu.ancestor.pdg)"
ancestor_parent_mom = "get_incident_momenta_rvec(dk2nu.ancestor)"
ancestor_incident_mom = "get_incident_momenta_rvec(dk2nu.ancestor)"
ancestor_produced_mom = "get_produced_momenta_rvec(dk2nu.ancestor)"
ancestor_produced_theta = "calc_theta_rvec(dk2nu.ancestor)"
ancestor_mass = "Numba::ancestor_pdg2mass(dk2nu.ancestor.pdg)"
ancestor_pT = "calc_pT_rvec(dk2nu.ancestor)"
ancestor_xF = "calc_xF_rvec(dk2nu.ancestor, ancestor_mass)"
is_nucleon_incident = "(ancestor_incident_pdg == 2212) || (ancestor_incident_pdg == 2112)"
is_nucleon_produced = "(ancestor_produced_pdg == 2212) || (ancestor_produced_pdg == 2112)"
is_proton_incident = "ancestor_incident_pdg == 2212"
is_proton_produced = "ancestor_produced_pdg == 2212"
#ivol = "interaction_volumes(ancestor.ivol)"
carbon_vol = "is_carbon_volume(dk2nu.ancestor)"
neg_xF = "(ancestor_xF < 0.0) && (ancestor_xF >= -0.25)"
in_PS = "(ancestor_pT < 2.0) && (ancestor_incident_mom > 12.0)"
in_CPS = "carbon_vol && (ancestor_pT < 2.0) && (ancestor_incident_mom > 12.0)"
neg_xF_PS_NA = "neg_xF && in_PS && is_nucleon_incident"
qel = "is_nucleon_incident == is_nucleon_produced && ancestor_incident_pdg == ancestor_produced_pdg && (ancestor_xF > 0.95 || (ancestor_pT < ancestor_xF - 0.5))"
ancestor_xF_NA_8 = "ancestor_xF[is_nucleon_incident]"
ancestor_xF_NA = "ancestor_xF[is_nucleon_incident && !qel]"
ancestor_xF_NA_PS = "ancestor_xF[is_nucleon_incident && in_PS && !qel]"
ancestor_xF_NC_PS = "ancestor_xF[is_nucleon_incident && in_CPS && !qel]"
ancestor_xF_NC_OOPS = "ancestor_xF[is_nucleon_incident && carbon_vol && !qel]"
ancestor_xF_elastic = "ancestor_xF[is_nucleon_incident && qel]"
ancestor_pT_NA = "ancestor_pT[is_nucleon_incident]"
ancestor_incident_mom_NA = "ancestor_incident_mom[is_nucleon_incident]"
ancestor_produced_mom_NA = "ancestor_produced_mom[is_nucleon_incident]"
ancestor_produced_mom_NA_p = "ancestor_produced_mom[(ancestor_produced_pdg == 2212) && neg_xF_PS_NA]"
ancestor_produced_mom_NA_pip = "ancestor_produced_mom[(ancestor_produced_pdg == 211) && neg_xF_PS_NA]"
ancestor_produced_mom_NA_Kp = "ancestor_produced_mom[(ancestor_produced_pdg == 321) && neg_xF_PS_NA]"
ancestor_produced_theta_NA_p = "ancestor_produced_theta[(ancestor_produced_pdg == 2212) && neg_xF_PS_NA]"
ancestor_produced_theta_NA_pip = "ancestor_produced_theta[(ancestor_produced_pdg == 211) && neg_xF_PS_NA]"
ancestor_produced_theta_NA_Kp = "ancestor_produced_theta[(ancestor_produced_pdg == 321) && neg_xF_PS_NA]"

[histograms]
# Define histograms to create
# see ROOT::RDataFrame::Histo1D or ::Histo2D

## Figure 10
 [histograms.h_NC_PS]
 dir = "nucleon_interactions"
 title = "N+C in PS; xF; interactions"
 bins = [200, -2.0, 2.0]
 var = "ancestor_xF_NC_PS"
 weight = "flux_wgt"
 #filter = "is_nucleon_incident && in_CPS"
#
 [histograms.h_NC_OOPS]
 dir = "nucleon_interactions"
 title = "N+C OOPS; xF; interactions"
 bins = [200, -2.0, 2.0]
 var = "ancestor_xF_NC_OOPS"
 weight = "flux_wgt"
 #filter = "is_nucleon_incident && carbon_vol"
#
 [histograms.h_NA_PS]
 dir = "nucleon_interactions"
 title = "N+A PS; xF; interactions"
 bins = [200, -2.0, 2.0]
 var = "ancestor_xF_NA_PS"
 weight = "flux_wgt"
 #filter = "is_nucleon_incident && in_PS"
#
 [histograms.h_NA_OOPS]
 dir = "nucleon_interactions"
 title = "N+A OOPS; xF; interactions"
 bins = [200, -2.0, 2.0]
 var = "ancestor_xF_NA"
 weight = "flux_wgt"
 #filter = "is_nucleon_incident"
#
 [histograms.h_NA_elastic]
 dir = "nucleon_interactions"
 title = "N+A elastic; xF; interactions"
 bins = [200, -2.0, 2.0]
 var = "ancestor_xF_elastic"
 weight = "flux_wgt"
##################

## Figure 11
 [histograms.h_NA_pip]
 dir = "nucleon_interactions"
 title = "N+A #rightarrow #pi^{+}; p [GeV/c]; #theta [mrad]"
 xbins = [200, 0, 20]
 ybins = [500, 0, 500]
 xvar = "ancestor_produced_mom_NA_pip"
 yvar = "ancestor_produced_theta_NA_pip"
 weight = "flux_wgt"
#
[histograms.h_NA_Kp]
 dir = "nucleon_interactions"
 title = "N+A #rightarrow K^{+}; p [GeV/c]; #theta [mrad]"
 xbins = [200, 0, 20]
 ybins = [500, 0, 500]
 xvar = "ancestor_produced_mom_NA_Kp"
 yvar = "ancestor_produced_theta_NA_Kp"
 weight = "flux_wgt"
#
 [histograms.h_NA_p]
 dir = "nucleon_interactions"
 title = "N+A #rightarrow p; p [GeV/c]; #theta [mrad]"
 xbins = [200, 0, 20]
 ybins = [500, 0, 500]
 xvar = "ancestor_produced_mom_NA_p"
 yvar = "ancestor_produced_theta_NA_p"
 weight = "flux_wgt"
##################








